name: RUN python script
on:
  workflow_dispatch:
     inputs:
      name:
        description: 'hit the job'
        required: true
        default: 'run'
jobs:
  deploy:
    runs-on: self-hosted
    steps:
    - name : TEsting
      env :
        token : ${{secrets.VTAPI}}
      run: |
        pwd
        python3 pythonAPI.py -t $token
        
