name: RUN python script
on:
  workflow_dispatch:
     inputs:
      name:
        description: 'hit the job'
        required: true
        default: 'run'
jobs:
  deploy:
    runs-on: self-hosted
    steps:
    - name : Testing
      id: test1
      env :
        token : ${{secrets.VTAPI}}
      run: |
        pwd
        python3 pythonAPI.py -t token
    - name: check on failure
      if: steps.test1.outcome != 'success'
      run: python3 pythonAPI.py -t $token
        
        
