name: RUN python script
on:
  workflow_dispatch:
     inputs:
      name:
        description: 'hit the job'
        required: true
        default: 'run'
jobs:
  deploy:
    runs-on: self-hosted
    env :
        token : ${{secrets.VTAPI}}
    outputs:
      output1: ${{steps.test1.outputs.test}}
    steps:
    - name : Testing
      continue-on-error: true
      id: test1
      run: |
        pwd
        python3 pythonAPI.py -t $token
        echo "::set-output name=test::hello"
        
    - name: check on failure
      continue-on-error: true
      if: steps.test1.outcome == 'failure'
      run: python3 pythonAPI.py -t $token
    - name: retry
      continue-on-error: true
      id: retry1
      if: steps.test.outcome=='failure'
      run : python3 pythonAPI.py -t $token
    - name : regex_match
      id : reg1
      run : |
        echo ${{steps.test1.outputs.output1}}
        
      
    - name : Testing 2
      id : test2
      run : python3 pythonAPI.py -t $token
        
        
